project:
  type: default

format: 
  beamer:
    aspectration: 141
    theme: "Copenhagen"
    fonttheme: "structurebold"
    colortheme: "whale"
    header-includes:
      - \setbeamertemplate{items}[circle]
      - \setbeamertemplate{footline}{}
      - \usepackage{setspace}
      - \setbeamerfont{title}{size=\large}
      - \setbeamerfont{author}{size=\large}
      - \setbeamerfont{institute}{size=\small}
      - \setbeamerfont{date}{size=\small}
      - \setbeamertemplate{itemize/enumerate body begin}{\setlength{\itemsep}{2pt}\setlength{\parsep}{0pt}}
      - \setbeamertemplate{itemize/enumerate subbody begin}{\setlength{\itemsep}{1pt}\setlength{\parsep}{0pt}}
      - \definecolor{UBCblue}{rgb}{0.04706, 0.13725, 0.26667}
      - \usecolortheme[named=UBCblue]{structure}
      # - \useoutertheme[footline=authorinstitute]{miniframes}


